export const data = [
  {
    id:"product1",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/m/j/o/-original-imaghkvue4yjecju.jpeg?q=70",
    title: "Redmi Note 12 Pro 5G",
    reviews: "14,943 Ratings & 1,101 Reviews",
    prevPrice: 15999,
    newPrice: 12999,
    discount: '47%',
    company: "Redmi",
    color: "white",
    quantity: 1,
    category:"Mobiles",
    subcategory: "sneakers",
  },
  {
    id:"product2",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/l/8/d/-original-imagqadpnygfnn2v.jpeg?q=70",
    title: "Realme 11 Pro 5G",
    reviews: "14,943 Ratings & 1,101 Reviews",
    prevPrice: 22999,
    newPrice: 20999,
    discount: '47%',
    company: "Realme",
    color: "red",
    quantity: 1,
    category:"Mobiles",
    subcategory: "sneakers",
  },

  {
    id:"product3",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/3/5/l/-original-imaghx9qmgqsk9s4.jpeg?q=70",
    title: "Iphone 15 Pro Max",
    reviews: "14,943 Ratings & 1,101 Reviews",
    prevPrice: 60999,
    newPrice: 54999,
    discount: '47%',
    company: "Iphone",
    color: "green",
    quantity: 1,
    category:"Mobiles",
    subcategory: "sneakers",
  },
  {
    id:"product4",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/q/t/h/galaxy-f54-5g-sm-e546bzshins-samsung-original-imagq79f82pfyzvh.jpeg?q=70",
    title: "Samsung Galaxy M54 5G",
    reviews: "14,943 Ratings & 1,101 Reviews",
    prevPrice: 32999,
    newPrice: 30999,
    discount: '47%',
    company: "Samsung",
    color: "black",
    quantity: 1,
    category:"Mobiles",
    subcategory: "sneakers",
  },
  {
    id:"product5",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/5/y/8/-original-imagtt4mhqrzjs9r.jpeg?q=70",
    title: "vivo V29 5G (Red, 128 GB)  (8 GB RAM)",
    reviews: "14,943 Ratings & 1,101 Reviews",
    prevPrice: 34999,
    newPrice: 32999,
    discount: '47%',
    company: "Vivo",
    color: "green",
    quantity: 1,
    category:"Mobiles",
    subcategory: "flats",
  },
  {
    id:"product6",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/9/e/4/-original-imagtcrumzbqj4xd.jpeg?q=70",
    title: "OPPO Reno10 Pro 5G (Glossy Purple, 256 GB)  (12 GB RAM)",
    reviews: "14,943 Ratings & 1,101 Reviews",
    prevPrice: 32999,
    newPrice: 30999,
    discount: '47%',
    company: "Oppo",
    color: "black",
    quantity: 1,
    category:"Mobiles",
    subcategory: "flats",
  },

  {
    id:"product7",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/f/e/l/-original-imagnqpndcmxghyq.jpeg?q=70",
    title: "POCO X5 5G (Wildcat Blue, 256 GB)  (8 GB RAM)",
    reviews: "14,943 Ratings & 1,101 Reviews",
    prevPrice: 25999,
    newPrice: 22999,
    discount: '47%',
    company: "Poco",
    color: "white",
    quantity: 1,
    category:"Mobiles",
    subcategory: "flats",
  },

  {
    id:"product8",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/d/5/k/-original-imagtkzut72y6ddg.jpeg?q=70",
    title: "MOTOROLA Edge 40 Neo (Soothing Sea, 128 GB)  (8 GB RAM)",
    reviews: "14,943 Ratings & 1,101 Reviews",
    prevPrice: 33999,
    newPrice: 29999,
    discount: '47%',
    company: "Motorola",
    color: "green",
    quantity: 1,
    category:"Mobiles",
    subcategory: "sneakers",
  },

  {
    id:"product9",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/z/g/o/l-jc22-hd-fs-black-jmc-pckt-jump-cuts-original-imagg3yxshqtv3dk.jpeg?q=70",
    title: "Nike Men's Sneaker",
    reviews: "14,943 Ratings & 1,101 Reviews",
    prevPrice: 1499,
    newPrice: 450,
    company: "Jump cuts",
    color: "blue",
    category:"Fashion",
    quantity: 1,
    subcategory: "sneakers",
  },

  {
    id:"product10",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/s/c/p/m-db1024-15-3bros-original-imagz8zjfxthf7kn.jpeg?q=70",
    title: "Men Self Design Polo Neck Cotton Blend (220 gsm) Green T-Shirt",
    reviews: "1,28,268 ratings and 10,152 reviews",
    prevPrice: 1499,
    newPrice: 799,
    company: "Puma",
    color: "green",
    quantity: 1,
    category:"Fashion",
    subcategory: "sneakers",
  },
  {
    id:"product11",
    img: "https://rukminim2.flixcart.com/image/612/612/l45xea80/shirt/v/e/t/38-men-regular-slim-fit-solid-button-down-collar-formal-shirt-original-imagf4mxnhanzdtn.jpeg?q=70",
    title: "Men Slim Fit Solid Spread Collar Formal Shirt",
    reviews: "43,787 ratings and 3,430 reviews",
    prevPrice: 1499,
    newPrice: 469,
    company: "Puma",
    color: "red",
    quantity: 1,
    category:"Fashion",
    subcategory: "sneakers",
  },
  {
    id:"product12",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/q/h/6/m-check1195-tanip-original-imagrh2tzhwypbsg.jpeg?q=70",
    title: "Men Slim Fit Checkered Slim Collar Casual Shirt",
    reviews: "14,943 Ratings & 1,101 Reviews",
    prevPrice: 1499,
    newPrice: 349,
    company: "Puma",
    color: "black",
    quantity: 1,
    category:"Fashion",
    subcategory: "sneakers",
  },
  {
    id:"product13",
    img: "https://rukminim2.flixcart.com/image/612/612/kkr72q80/shirt/f/r/m/38-12442634-roadster-original-imagyyymzeytwzeg.jpeg?q=70",
    title: "Men Regular Fit Solid Mandarin Collar Casual Shirt",
    reviews: "39,172 ratings and 3,006 reviews",
    prevPrice: 1499,
    newPrice: 299,
    company: "Puma",
    color: "white",
    quantity: 1,
    category:"Fashion",
    subcategory: "sneakers",
  },
  {
    id:"product14",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/p/g/x/s-st1-vebnor-original-imagn7hdggmex5bw.jpeg?q=70",
    title: "Men Regular Fit Solid Mandarin Collar Casual Shirt",
    reviews: "1,22,580 ratings and 9,438 reviews",
    prevPrice: 1499,
    newPrice: 350,
    company: "Puma",
    color: "black",
    quantity: 1,
    category:"Fashion",
    subcategory: "sneakers",
  },

  {
    id:"product15",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sweatshirt/n/p/q/l-r-mens-highneck-01-black-plus91-original-imagkc9fkqzcgdr7.jpeg?q=70",
    title: "Men Solid High Neck Wool Blend Black T-Shirt",
    reviews: "1,679 ratings and 109 reviews",
    prevPrice: 1499,
    newPrice: 419,
    company: "Puma",
    color: "green",
    quantity: 1,
    category:"Fashion",
    subcategory: "sneakers",
  },
  {
    id:"product16",
    img: "https://rukminim2.flixcart.com/image/612/612/kzn17680/shirt/0/q/o/l-logo-shirt-infinity-choice-original-imagbhwczbphzk5f.jpeg?q=70",
    title: "Men Regular Fit Solid Spread Collar Casual Shirt",
    reviews: "26,582 ratings and 1,065 reviews",
    prevPrice:1499,
    newPrice: 419,
    company: "Vans",
    color: "red",
    quantity: 1,
    category:"Fashion",
    subcategory: "flats",
  },
  {
    id:"product17",
    img: "https://rukminim2.flixcart.com/image/612/612/kxhvf680/mouse/d/1/p/toad-14-portronics-original-imag9xnpexundzez.jpeg?q=70",
    title: "Portronics Toad 14 Wireless Optical Mouse  (2.4GHz Wireless, Black)",
    reviews: "27,729 Ratings & 2,972 Reviews",
    prevPrice: 1499,
    newPrice: 419,
    company: "Vans",
    color: "white",
    quantity: 1,
    category:"Electronics",
    subcategory: "sandals",
  },
  {
    id:"product18",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/keyboard/laptop-keyboard/0/s/d/key6-combo-keyboard-mouse-combo-set-with-2-4ghz-adjustable-dpi-original-imagszg9pn5tdahw.jpeg?q=70",
    title: "Portronics Key6 Combo with 2.4Ghz, Adjustable DPI, Silent Keys Wireless Laptop Keyboard  (Black)",
    reviews: "29,777 Ratings & 3,575 Reviews",
    prevPrice: 1499,
    newPrice: 419,
    company: "Vans",
    color: "blue",
    quantity: 1,
    category:"Electronics",
    subcategory: "sandals",
  },
  {
    id:"product19",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/l/o/f/-original-imagsd63zhddzayv.jpeg?q=70",
    title: "Boult Audio W40 with Quad Mic ENC, 48H Battery Life, Low Latency Gaming, Made in India, 5.3v Bluetooth Headset  (Denim Blue, True Wireless)",
    reviews: "20,241 Ratings & 2,584 Reviews",
    prevPrice: 1499,
    newPrice: 469,
    company: "Nike",
    color: "black",
    quantity: 1,
    category:"Electronics",
    subcategory: "sandals",
  },
  {
    id:"product20",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/i/x/x/wh-ch510-sony-original-imagz5r5qqrsfteq.jpeg?q=70",
    title: "SONY WH-CH520 with 50 Hrs Playtime, DSEE Upscale, Multipoint Connection/Dual Pairing Bluetooth Headset  (Black, On the Ear)",
    reviews: "1,878 Ratings & 196 Reviews",
    prevPrice: 1499,
    newPrice: 399,
    company: "Vans",
    color: "black",
    quantity: 1,
    category:"Electronics",
    subcategory: "heels",
  },
  {
    id:"product21",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/k/q/b/-original-imagt7b2f2mhgjpn.jpeg?q=70",
    title: "Mivi Fort S660 With Dolby Audio, 2 Satellite Speakers, Surround Sound 660 W Bluetooth Soundbar  (Black, 5.1 Channel)",
    reviews: "4,524 Ratings & 678 Reviews",
    prevPrice: 1499,
    newPrice: 419,
    company: "puma",
    color: "black",
    quantity: 1,
    category:"Electronics",
    subcategory: "heels",
  },
  {
    id:"product22",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/n/n/q/-original-imagu3kmvtfdy5hk.jpeg?q=70",
    title: "Lenovo IdeaPad Gaming 3 Intel Core i5 11th Gen 11320H - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce GTX 1650) 15IHU6 Gaming Laptop  (15.6 Inch, Shadow Black, 2.25 kg)",
    reviews: "4,675 Ratings & 419 Reviews",
    prevPrice: 1499,
    newPrice: 489,
    company: "Nike",
    color: "red",
    quantity: 1,
    category:"Electronics",
    subcategory: "heels",
  },
  {
    id:"product23",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/pocket-printer/u/o/t/bt-58-bluetooth-niyama-1-original-imaghr46havrhen4.jpeg?q=70",
    title: "Niyama BT-58 Thermal Receipt Printer",
    reviews: "1116 Ratings & 6 Reviews",
    prevPrice: 1499,
    newPrice: 439,
    company: "Nike",
    color: "red",
    quantity: 1,
    category:"Electronics",
    subcategory: "sneakers",
  },

  {
    id:"product24",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/memory-card/microsd-card/q/o/b/sdsqxav-1t00-gn6mn-sandisk-original-imaggvvz4kz9znjt.jpeg?q=70",
    title: "SanDisk Ultra 256 GB MicroSDXC Class 10 150 MB/s Memory Card",
    reviews: "4,880 Ratings & 397 Reviews",
    prevPrice: 1499,
    newPrice: 439,
    company: "Nike",
    color: "black",
    quantity: 1,
    category:"Electronics",
    subcategory: "heels",
  },
  {
    id:"product25",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/n/b/f/65ca-vu-original-imaguf4xxzmtfegg.jpeg?q=70",
    title: "Vu 164 cm (65 inch) Ultra HD (4K) LED Smart Google TV  (65CA)",
    reviews: "4 Ratings & 0 Reviews",
    prevPrice: 1499,
    newPrice: 599,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Tv",
    subcategory: "heels",
  },
  {
    id:"product26",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/v/x/n/-original-imaguem7rhy9zzrf.jpeg?q=70",
    title: "SONY 138.8 cm (55 inch) Ultra HD (4K) LED Smart Google TV 2022 Edition  (KD-55X74K)",
    reviews: "14,469 Ratings & 2,831 Reviews",
    prevPrice: 1499,
    newPrice: 489,
    company: "Adidas",
    color: "white",
    quantity: 1,
    category:"Tv",
    subcategory: "heels",
  },
  {
    id:"product27",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/refrigerator-new/8/u/4/-original-imagrt57je6csdsx.jpeg?q=70",
    title: "Haier 596 L Frost Free Side by Side Convertible Refrigerator  (Shiny Steel, HES-690SS-P)",
    reviews: "121 Ratings & 12 Reviews",
    prevPrice: 1499,
    newPrice: 899,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Tv",
    subcategory: "heels",
  },
  {
    id:"product28",
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/air-conditioner-new/9/v/m/-original-imagmnmtvz83h39z.jpeg?q=70",
    title: "LG 1.5 Ton 5 Star Split Dual Inverter AC - White  (RS-Q19BNZE, Copper Condenser)",
    reviews: "28,123 Ratings & 2,874 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Tv",
    subcategory: "flats",
  },
  {
    id:"product29",
    img: "https://rukminim2.flixcart.com/image/612/612/ko0d6kw0/mixer-grinder-juicer/0/h/u/plus-butterfly-original-imag2kadbfjzzayj.jpeg?q=70",
    title: "Butterfly Rapid plus / Rapid Plus 5J 750 W Juicer Mixer Grinder (5 Jars, Ink Blue)",
    reviews: "1,31,651 Ratings & 12,790 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Tv",
    subcategory: "flats",
  },
  {
    id:"product30",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/washing-machine-new/3/c/d/-original-imagteu9vxf7hdt2.jpeg?q=70",
    title: "IFB 6 kg Steam Wash, Hard Water Wash, Active Color ",
    reviews: "80,913 Ratings & 8,365 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Tv",
    subcategory: "flats",
  },
  {
    id:"product31",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/water-purifier/h/u/3/glory-aquaguard-original-imagnc64fcqauhgq.jpeg?q=70",
    title: "Aquaguard Glory 6 L RO + UV + UF + MTDS Water Purifier Active Copper technology  (Black)",
    reviews: "2,511 Ratings & 344 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Tv",
    subcategory: "flats",
  },
  {
    id:"product32",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/water-geyser/l/t/l/-original-imagspcnpqvmzjjc.jpeg?q=70",
    title: "BAJAJ 25 L Storage Water Geyser Suitable for large wall spaces (Popular Plus 25 L, White)",
    reviews: "35,693 Ratings & 2,932 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Tv",
    subcategory: "flats",
  },
  {
    id:"product33",
    img: "https://rukminim2.flixcart.com/image/612/612/kzrbiq80/moisturizer-cream/5/l/d/-original-imagbzy4cqzgufma.jpeg?q=70",
    title: "NIVEA Body Milk Nourishing Body Lotion 400ml & 120 ml - Pack of 2  (520 ml)",
    reviews: "1,61,091 Ratings & 12,268 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Beauty",
    subcategory: "flats",
  },
  {
    id:"product34",
    img: "https://rukminim2.flixcart.com/image/612/612/klcmoi80/body-skin-treatment/k/p/7/skin-care-charcoal-blackhead-remover-nose-strips-hip-hop-original-imagyhrfzm6zh89k.jpeg?q=70",
    title: "Hip Hop Skin Care Charcoal Blackhead Remover Nose Strips  (6 g)",
    reviews: "34,790 Ratings & 2,878 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Beauty",
    subcategory: "flats",
  },
  {
    id:"product35",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/face-wash/v/d/j/100-ubtan-natural-face-wash-for-dry-skin-with-turmeric-saffron-original-imagbf3j6u4fgx46.jpeg?q=70",
    title: "Mamaearth Ubtan Natural for Dry Skin with Turmeric & Saffron for Tan removal and Skin brightning - SLS & Paraben Free Face Wash  (100 ml)",
    reviews: "3,67,545 Ratings & 27,971 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Beauty",
    subcategory: "flats",
  },
  {
    id:"product36",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/moisturizer-cream/z/e/d/-original-imagtjhrfuyjukrf.jpeg?q=70",
    title: "BOROPLUS Doodh Kesar Lotion 400ml - Pack of 2  (800 ml)",
    reviews: "1,43,909 Ratings & 11,643 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Beauty",
    subcategory: "flats",
  },
  {
    id:"product37",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/milk-drink-mix/s/o/c/-original-imagp8wcfzs2tgwm.jpeg?q=70",
    title: "HORLICKS Classic Malt  (2 kg)",
    reviews: "35,693 Ratings & 2,932 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Beauty",
    subcategory: "flats",
  },
  {
    id:"product38",
    img: "https://rukminim2.flixcart.com/image/612/612/kq5iykw0/soap/c/w/l/pure-gentle-bathing-bar-pears-original-imag48gchwfybcch.jpeg?q=70",
    title: "Pears P & G BATHING BAR WITH Glycerin and Natural Oils  (8 x 125 g)",
    reviews: "2,57,987 Ratings & 19,080 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Beauty",
    subcategory: "flats",
  },
  {
    id:"product39",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/hair-volumizer/c/u/0/5-hair-volumizing-powder-wax-with-strong-hold-matte-finish-for-original-imagm736d6wugtxn.jpeg?q=70",
    title: "Dabur Red Toothpaste  (1000 g, Pack of 2)",
    reviews: "29,220 Ratings & 2,251 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Beauty",
    subcategory: "flats",
  },
  {
    id:"product40",
    img: "https://rukminim2.flixcart.com/image/612/612/ktizdzk0/soap/e/m/i/antiseptic-plus-moisturising-soap-neem-tulsi-and-aloe-vera-original-imag6umbveebkeqp.jpeg?q=70",
    title: "BOROPLUS Antiseptic + Moisturising Soap - Neem, Tulsi & Aloe Vera  (6 x 125 g)",
    reviews: "9,817 Ratings & 641 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Beauty",
    subcategory: "flats",
  },
  {
    id:"product41",
    img: "https://rukminim2.flixcart.com/image/612/612/ktuewsw0/painting/y/p/j/indr1317-indianara-original-imag73tar2bnhrdz.jpeg?q=70",
    title: "Indianara GANESHA PAINTING (1317) Digital Reprint 13 inch x 10.6 inch Painting  (With Frame)",
    reviews: "6,757 Ratings & 737 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Home",
    subcategory: "flats",
  },
  {
    id:"product42",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/painting/f/a/e/9-1-g129-interio-crafts-original-imagsgnh7gggvjsm.jpeg?q=70",
    title: "Interio Crafts Adiyogi Shiva Room Wall Art Digital Reprint 13 inch x 9 inch Painting  (With Frame)",
    reviews: "9,817 Ratings & 641 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Home",
    subcategory: "flats",
  },
  {
    id:"product43",
    img: "https://rukminim2.flixcart.com/image/612/612/krtjgcw0/showpiece-figurine/q/8/d/sg-royalbox-original-imag5gy2rxubzkgq.jpeg?q=70",
    title: "Royalbox Meditating Buddha Statue For Home Decor Idol/Showpiece Decorative Showpiece - 17",
    reviews: "5,692 Ratings & 522 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Home",
    subcategory: "flats",
  },
  {
    id:"product44",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/showpiece-figurine/l/6/z/10-10-gram1-fashion-bizz-23-original-imagnu3csndwzzzy.jpeg?q=70",
    title: "Fashion Bizz Antique Handmade Vintage Dummy Gramophone Decorative Showpiece - 23 cm  (Brass, Wood, Gold)",
    reviews: "17,454 Ratings & 1,712 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Home",
    subcategory: "flats",
  },
  {
    id:"product45",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/rice-light/z/h/r/40-bulb-11-1-11m-40l-multicolor-power-pixel-mprow-original-imaguf4fx6jyxfmg.jpeg?q=70",
    title: "MPROW 40 LEDs 11 m Multicolor Steady Bulb Rice Lights  (Pack of 1)",
    reviews: "4,362 Ratings & 270 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Home",
    subcategory: "flats",
  },
  {
    id:"product46",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/table-lamp/g/n/d/aries-6w-rechargeable-led-with-3-grade-dimming-touch-control-original-imagn5mhz43hzzsu.jpeg?q=70",
    title: "Wipro Aries 6W Rechargeable LED with 3 grade dimming|Touch control|Upto 5 Hrs backup Table Lamp  (36.3 cm, White)",
    reviews: "606 Ratings & 47 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Home",
    subcategory: "flats",
  },
  {
    id:"product47",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/aquarium-filter/g/w/i/100-aquarium-filter-buraq-original-imagqfrzdshyvnwk.jpeg?q=70",
    title: "Buraq Aquarium Filter Pump 3 in 1 High Power Oxygen Filteration System Power Aquarium Filter  (Mechanical Filtration for Fresh Water)",
    reviews: "1,987 Ratings & 182 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Home",
    subcategory: "flats",
  },
  {
    id:"product48",
    img: "https://rukminim2.flixcart.com/image/612/612/kqo3onk0/wall-clock/g/k/u/fancy-and-designer-wall-clock-for-home-offices-bedroom-living-original-imag4hyvahrggekr.jpeg?q=70",
    title: "R&P ENTERPRISE Analog 65 cm X 35 cm Wall Clock  (Black, Red, Without Glass, Standard)",
    reviews: "30,288 Ratings & 3,946 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Home",
    subcategory: "flats",
  },
  {
    id:"product49",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/wardrobe-closet/y/2/h/-original-imagh3vpqe9npwhj.jpeg?q=70",
    title: "SPACEWOOD Apex Engineered Wood 3 Door Wardrobe ",
    reviews: "990 Ratings & 129 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Furniture",
    subcategory: "flats",
  },
 
  {
    id:"product50",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/sofa-sectional/y/y/i/-original-imagqz224qqg3yfz.jpeg?q=70",
    title: "Bharat Lifestyle Lexus Fabric 3 Seater Sofa  (Finish Color - Grey, DIY(Do-It-Yourself))",
    reviews: "714 Ratings & 93 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Furniture",
    subcategory: "flats",
  },
  {
    id:"product51",
    img: "https://rukminim2.flixcart.com/image/612/612/k5cs87k0/bed/d/u/x/queen-na-particle-board-ams123-bharat-lifestyle-matte-original-imafz2yvwcmkfyrb.jpeg?q=70",
    title: "Bharat Lifestyle Amsterdam Engineered Wood Queen Bed  (Finish Color - Wenge, Delivery Condition - Knock Down)",
    reviews: "8,345 Ratings & 965 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Furniture",
    subcategory: "flats",
  },
  {
    id:"product52",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/tv-entertainment-unit/s/g/p/-original-imagrtbkkrxfdxeu.jpeg?q=70",
    title: "Flipkart Perfect Homes Webster Engineered Wood TV Entertainment Unit  (Finish Color - Almond Walnut, Knock Down)",
    reviews: "2,227 Ratings & 411 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Furniture",
    subcategory: "flats",
  },
  {
    id:"product53",
    img: "https://rukminim2.flixcart.com/image/612/612/kk2wl8w0/computer-table/v/r/o/particle-board-bst-ebee-wenge-original-imafzg73dbqruhrt.jpeg?q=70",
    title: "Ebee Engineered Wood Computer Desk  (Modular, Finish Color - Wenge, DIY(Do-It-Yourself))",
    reviews: "5,368 Ratings & 690 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Furniture",
    subcategory: "flats",
  },
  {
    id:"product54",
    img: "https://rukminim2.flixcart.com/image/612/612/kyj0vbk0/shoe-rack/t/c/p/br-almari-cgul-brown-original-imagaqs5whf4d3gy.jpeg?q=70",
    title: "LAO Carbon Steel Collapsible Wardrobe  (Finish Color - SKY BLUE, DIY(Do-It-Yourself))",
    reviews: "5,619 Ratings & 418 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Furniture",
    subcategory: "flats",
  },
  {
    id:"product55",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/dining-set/g/o/a/-original-imagtjkgkfxhpnrw.jpeg?q=70",
    title: "Flipkart Perfect Homes Capri Engineered Wood 6 Seater Dining Set  (Finish Color -Walnut, Knock Down)",
    reviews: "1,482 Ratings & 246 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Furniture",
    subcategory: "flats",
  },
  {
    id:"product56",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/blanket/t/p/j/400-gsm-winter-1-6-kg-double-bed-blanket-cs0240302-spangle-original-imagreyyxkckatuq.jpeg?q=70",
    title: "SPANGLE 3D Printed Double Mink Blanket for Mild Winter  (Microfiber, Diamond Blue)",
    reviews: "27 Ratings & 4 Reviews",
    prevPrice: 1499,
    newPrice: 999,
    company: "Adidas",
    color: "black",
    quantity: 1,
    category:"Furniture",
    subcategory: "flats",
  },
];

export default data;